[build]
builder = "NIXPACKS"
buildCommand = "cd medusa-backend && npm install"

[deploy]
startCommand = "cd medusa-backend && node --loader tsx ./node_modules/.bin/medusa start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/health"
timeout = 300
